# -*- coding: utf-8 -*-
"""EDA 1 - StudentsPerformance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T0SukoKHhlmB9s-N9oeLHKJ5MUaTunkr

# EDA - Exploratory Data Analysis

# Importing Packages
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
# %matplotlib inline

"""# Loading the dataset"""

df_train = pd.read_csv("students_train.csv")
df_test = pd.read_csv("students_test.csv")
# data = pd.read_csv("https://raw.githubusercontent.com/rahulinchal/EDA-on-StudentsPerformance/main/StudentsPerformance.csv")

"""# Head =  first 5 rows"""

df_train.head()

"""# Tail = last 5 rows

"""

df_train.tail()

"""# Data Statistics

"""

df_train.sample(10)

df_train.shape

df_train.info()

df_train.describe()

df_train.nunique()

df_train["parental level of education"].unique()

df_train["race/ethnicity"].value_counts()

"""# Data Visualisation"""

# No of males and females
sns.countplot(x='gender', data=df_train)

# How many students of each gender completed course?
sns.countplot(x='gender',hue="test preparation course",data=df_train)

# Students of which age group are good and well prepared with math?
sns.barplot(x='race/ethnicity',y="math score",data=df_train)

# How is the reading score distribution amount the students?
sns.histplot(df_train['reading score'],color='red')

df_train.head()

"""# Data Cleaning"""

#Step 2. Quick data cleaning and pre-processing

# Drop race/ethnictity and parental level of education column
# Binary encode Sex column

# Dropping tables
df_tain = df_train.drop(["race/ethnicity","parental level of education"], axis =1)



"""# Correaltion = Mutual relationship"""

correlation = df_train.corr()

sns.heatmap(correlation , annot = True)

sns.pairplot(df_train)

sns.relplot(x= "math score", y = "reading score", hue = "gender", data = df_train)